### ISSUE TITLE
rdp

### ISSUE THREAD

**Issue by yhy0** [b1gcat/DarkEye#7]
4.2的rdp
去除if判断后
![image](https://user-images.githubusercontent.com/31311038/123209953-ecce0c00-d4f3-11eb-81d1-346d833ce107.png)

这个是怎么解决的？新版为啥没有了rdp？求教

**Comment by b1gcat** [comment]
根据系统自行编译或下载libfreerdp的开发包就行， 去除的原因自己电脑跑的很好，但是其它系统就是兼容性不是很好 。精力不够去搞了。
